packages:
    asm89/stack-cors: 1.2.0
    behat/behat: v3.5.0
    behat/gherkin: v4.6.0
    behat/mink: v1.7.1
    behat/mink-browserkit-driver: 1.3.3
    behat/mink-extension: 2.3.1
    behat/mink-goutte-driver: v1.2.1
    behat/mink-selenium2-driver: v1.3.1
    behat/transliterator: v1.2.0
    brainmaestro/composer-git-hooks: v2.7.1
    brumann/polyfill-unserialize: v1.0.3
    chi-teck/drupal-code-generator: 1.30.3
    composer/installers: v1.6.0
    composer/semver: 1.5.0
    consolidation/annotated-command: 2.12.0
    consolidation/config: 1.2.1
    consolidation/filter-via-dot-access-data: 1.0.0
    consolidation/log: 1.1.1
    consolidation/output-formatters: 3.5.0
    consolidation/robo: 1.4.9
    consolidation/self-update: 1.1.5
    consolidation/site-alias: 3.0.0
    consolidation/site-process: 2.0.3
    container-interop/container-interop: 1.2.0
    cweagans/composer-patches: 1.6.6
    dealerdirect/phpcodesniffer-composer-installer: v0.5.0
    dflydev/dot-access-data: v1.1.0
    dnoegel/php-xdg-base-dir: '0.1'
    doctrine/annotations: v1.6.1
    doctrine/cache: v1.8.0
    doctrine/collections: v1.5.0
    doctrine/common: v2.10.0
    doctrine/event-manager: v1.0.0
    doctrine/inflector: v1.3.0
    doctrine/instantiator: 1.2.0
    doctrine/lexer: 1.0.2
    doctrine/persistence: 1.1.1
    doctrine/reflection: v1.0.0
    drupal-composer/drupal-scaffold: 2.6.1
    drupal/admin_toolbar: 1.27.0
    drupal/captcha: 1.0.0-beta1
    drupal/cdn: 3.3.0
    drupal/coder: 8.3.5
    drupal/core: 8.7.3
    drupal/crop: 1.5.0
    drupal/ctools: 3.2.0
    drupal/dropzonejs: 2.0.0-alpha4
    drupal/drupal-driver: v1.4.0
    drupal/drupal-extension: v3.4.1
    drupal/entity_browser: 2.1.0
    drupal/entity_browser_entity_form: 2.1.0
    drupal/entity_reference_revisions: 1.6.0
    drupal/focal_point: 1.0.0
    drupal/hide_revision_field: 2.1.0
    drupal/high_contrast: 1.0.0-beta1
    drupal/inline_entity_form: 1.0.0-rc1
    drupal/inline_responsive_images: 2.1.0
    drupal/key: 1.8.0
    drupal/link_attributes: 1.8.0
    drupal/linkit: 4.3.0
    drupal/mailsystem: 4.1.0
    drupal/media_entity_browser: 2.0.0-alpha2
    drupal/menu_block: 1.5.0
    drupal/menu_block_current_language: 1.2.0
    drupal/menu_trail_by_path: 1.1.0
    drupal/paragraphs: 'dev-1.x:7e501a5f248b739500f5ac9e55fa779048b80ead'
    drupal/pathauto: 1.4.0
    drupal/publication_date: 2.0.0-beta1
    drupal/rabbit_hole: 1.0.0-beta6
    drupal/recaptcha: 2.4.0
    drupal/redirect: 1.4.0
    drupal/scheduler: 'dev-1.x:63b5ca8c1205e8cd047d8f85014fbc3c203d56ba'
    drupal/select2: 1.1.0
    drupal/smart_trim: 1.1.0
    drupal/svg_image: 1.9.0
    drupal/swiftmailer: 1.0.0-beta2
    drupal/system_status: 2.8.0
    drupal/token: 1.5.0
    drupal/twig_tweak: 2.3.0
    drupal/video_embed_field: 2.1.0
    drupal/view_unpublished: 1.0.0-alpha1
    drupal/webform: 5.2.0
    drush/drush: 9.7.1
    easyrdf/easyrdf: 0.9.1
    egulias/email-validator: 2.1.9
    enyo/dropzone: 5.5.0
    fabpot/goutte: v3.2.3
    grasmash/expander: 1.0.0
    grasmash/yaml-expander: 1.4.0
    guzzlehttp/guzzle: 6.3.3
    guzzlehttp/promises: v1.3.1
    guzzlehttp/psr7: 1.6.1
    html2text/html2text: 4.0.1
    instaclick/php-webdriver: 1.4.5
    jakub-onderka/php-console-color: v0.2
    jakub-onderka/php-console-highlighter: v0.4
    league/container: 2.4.1
    masterminds/html5: 2.6.0
    myclabs/deep-copy: 1.9.1
    nikic/php-parser: v4.2.2
    paragonie/random_compat: v9.99.99
    pear/archive_tar: 1.4.7
    pear/console_getopt: v1.4.2
    pear/pear-core-minimal: v1.10.9
    pear/pear_exception: v1.0.0
    phar-io/manifest: 1.0.1
    phar-io/version: 1.0.1
    phpdocumentor/reflection-common: 1.0.1
    phpdocumentor/reflection-docblock: 4.3.1
    phpdocumentor/type-resolver: 0.4.0
    phpspec/prophecy: 1.8.1
    phpunit/php-code-coverage: 5.3.2
    phpunit/php-file-iterator: 1.4.5
    phpunit/php-text-template: 1.2.1
    phpunit/php-timer: 1.0.9
    phpunit/php-token-stream: 2.0.2
    phpunit/phpunit: 6.5.14
    phpunit/phpunit-mock-objects: 5.0.10
    psr/container: 1.0.0
    psr/http-message: 1.0.1
    psr/log: 1.1.0
    psy/psysh: v0.9.9
    ralouphie/getallheaders: 3.0.3
    sebastian/code-unit-reverse-lookup: 1.0.1
    sebastian/comparator: 2.1.3
    sebastian/diff: 2.0.1
    sebastian/environment: 3.1.0
    sebastian/exporter: 3.1.0
    sebastian/global-state: 2.0.0
    sebastian/object-enumerator: 3.0.3
    sebastian/object-reflector: 1.1.1
    sebastian/recursion-context: 3.0.0
    sebastian/resource-operations: 1.0.0
    sebastian/version: 2.0.1
    select2/select2: 4.0.7
    sortablejs/sortable: 1.8.4
    squizlabs/php_codesniffer: 3.4.2
    stack/builder: v1.0.5
    swiftmailer/swiftmailer: v5.4.12
    symfony-cmf/routing: 1.4.1
    symfony/browser-kit: v3.4.29
    symfony/class-loader: v3.4.29
    symfony/config: v3.4.29
    symfony/console: v3.4.29
    symfony/css-selector: v3.4.29
    symfony/debug: v3.4.29
    symfony/dependency-injection: v3.4.29
    symfony/dom-crawler: v3.4.29
    symfony/event-dispatcher: v3.4.29
    symfony/filesystem: v3.4.29
    symfony/finder: v3.4.29
    symfony/http-foundation: v3.4.29
    symfony/http-kernel: v3.4.29
    symfony/polyfill-ctype: v1.11.0
    symfony/polyfill-iconv: v1.11.0
    symfony/polyfill-mbstring: v1.11.0
    symfony/polyfill-php70: v1.11.0
    symfony/process: v3.4.29
    symfony/psr-http-message-bridge: v1.2.0
    symfony/routing: v3.4.29
    symfony/serializer: v3.4.29
    symfony/translation: v3.4.29
    symfony/validator: v3.4.29
    symfony/var-dumper: v3.4.29
    symfony/yaml: v3.4.29
    theseer/tokenizer: 1.1.3
    twig/twig: v1.42.2
    typo3/phar-stream-wrapper: v2.1.2
    webflo/drupal-finder: 1.1.0
    webmozart/assert: 1.4.0
    webmozart/path-util: 2.3.0
    zendframework/zend-diactoros: 1.8.6
    zendframework/zend-escaper: 2.6.0
    zendframework/zend-feed: 2.12.0
    zendframework/zend-stdlib: 3.2.1
