roleassign_roles:
  content_producer: content_producer
  editor_in_chief: editor_in_chief
  administrator: administrator
  webform_administrator: webform_administrator
_core:
  default_config_hash: iKucdYPrf1EPMz6Y3s71EADiRcAiwoLTIw9_JoxH-Jg
